[2025-05-05 14:24:10,323] {processor.py:153} INFO - Started process (PID=8690) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:24:10,323] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:24:10,324] {logging_mixin.py:115} INFO - [2025-05-05 14:24:10,323] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:24:10,329] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:24:10,367] {logging_mixin.py:115} INFO - [2025-05-05 14:24:10,367] {manager.py:508} INFO - Created Permission View: can delete on DAG:dados_climaticos
[2025-05-05 14:24:10,375] {logging_mixin.py:115} INFO - [2025-05-05 14:24:10,375] {manager.py:508} INFO - Created Permission View: can edit on DAG:dados_climaticos
[2025-05-05 14:24:10,383] {logging_mixin.py:115} INFO - [2025-05-05 14:24:10,383] {manager.py:508} INFO - Created Permission View: can read on DAG:dados_climaticos
[2025-05-05 14:24:10,383] {logging_mixin.py:115} INFO - [2025-05-05 14:24:10,383] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:24:10,387] {logging_mixin.py:115} INFO - [2025-05-05 14:24:10,387] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2025-05-05 14:24:10,391] {logging_mixin.py:115} INFO - [2025-05-05 14:24:10,391] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:24:10,402] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.080 seconds
[2025-05-05 14:24:42,995] {processor.py:153} INFO - Started process (PID=8814) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:24:42,996] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:24:42,996] {logging_mixin.py:115} INFO - [2025-05-05 14:24:42,996] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:24:43,000] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:24:43,013] {logging_mixin.py:115} INFO - [2025-05-05 14:24:43,013] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:24:43,024] {logging_mixin.py:115} INFO - [2025-05-05 14:24:43,024] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:24:43,035] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.042 seconds
[2025-05-05 14:25:17,779] {processor.py:153} INFO - Started process (PID=8953) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:25:17,780] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:25:17,780] {logging_mixin.py:115} INFO - [2025-05-05 14:25:17,780] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:25:17,784] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:25:17,793] {logging_mixin.py:115} INFO - [2025-05-05 14:25:17,792] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:25:17,801] {logging_mixin.py:115} INFO - [2025-05-05 14:25:17,801] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:25:17,810] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.032 seconds
[2025-05-05 14:25:52,269] {processor.py:153} INFO - Started process (PID=9091) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:25:52,269] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:25:52,270] {logging_mixin.py:115} INFO - [2025-05-05 14:25:52,269] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:25:52,273] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:25:52,281] {logging_mixin.py:115} INFO - [2025-05-05 14:25:52,281] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:25:52,290] {logging_mixin.py:115} INFO - [2025-05-05 14:25:52,290] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:25:52,300] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.033 seconds
[2025-05-05 14:26:23,667] {processor.py:153} INFO - Started process (PID=9215) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:26:23,668] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:26:23,668] {logging_mixin.py:115} INFO - [2025-05-05 14:26:23,668] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:26:23,673] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:26:23,687] {logging_mixin.py:115} INFO - [2025-05-05 14:26:23,687] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:26:23,698] {logging_mixin.py:115} INFO - [2025-05-05 14:26:23,698] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:26:23,710] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.045 seconds
[2025-05-05 14:26:59,311] {processor.py:153} INFO - Started process (PID=9360) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:26:59,311] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:26:59,311] {logging_mixin.py:115} INFO - [2025-05-05 14:26:59,311] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:26:59,315] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:26:59,323] {logging_mixin.py:115} INFO - [2025-05-05 14:26:59,323] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:26:59,331] {logging_mixin.py:115} INFO - [2025-05-05 14:26:59,331] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:26:59,339] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.030 seconds
[2025-05-05 14:27:32,214] {processor.py:153} INFO - Started process (PID=9484) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:27:32,214] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:27:32,215] {logging_mixin.py:115} INFO - [2025-05-05 14:27:32,215] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:27:32,218] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:27:32,229] {logging_mixin.py:115} INFO - [2025-05-05 14:27:32,229] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:27:32,241] {logging_mixin.py:115} INFO - [2025-05-05 14:27:32,240] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:27:32,251] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.038 seconds
[2025-05-05 14:28:08,139] {processor.py:153} INFO - Started process (PID=9629) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:28:08,139] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:28:08,139] {logging_mixin.py:115} INFO - [2025-05-05 14:28:08,139] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:28:08,141] {logging_mixin.py:115} INFO - [2025-05-05 14:28:08,140] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 17
    tarefa_2 = PythonOperator(
IndentationError: unexpected indent
[2025-05-05 14:28:08,141] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:28:08,157] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.020 seconds
[2025-05-05 14:28:42,724] {processor.py:153} INFO - Started process (PID=9767) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:28:42,725] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:28:42,725] {logging_mixin.py:115} INFO - [2025-05-05 14:28:42,725] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:28:42,727] {logging_mixin.py:115} INFO - [2025-05-05 14:28:42,726] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 17
    tarefa_2 = PythonOperator(
IndentationError: unexpected indent
[2025-05-05 14:28:42,727] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:28:42,742] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.019 seconds
[2025-05-05 14:29:15,921] {processor.py:153} INFO - Started process (PID=9899) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:29:15,921] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:29:15,922] {logging_mixin.py:115} INFO - [2025-05-05 14:29:15,922] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:29:15,923] {logging_mixin.py:115} INFO - [2025-05-05 14:29:15,922] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 17
    tarefa_2 = PythonOperator(
IndentationError: unexpected indent
[2025-05-05 14:29:15,923] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:29:15,935] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.015 seconds
[2025-05-05 14:29:46,655] {processor.py:153} INFO - Started process (PID=10020) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:29:46,655] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:29:46,656] {logging_mixin.py:115} INFO - [2025-05-05 14:29:46,655] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:29:46,657] {logging_mixin.py:115} INFO - [2025-05-05 14:29:46,657] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 17
    tarefa_2 = PythonOperator(
IndentationError: unexpected indent
[2025-05-05 14:29:46,657] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:29:46,670] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.017 seconds
[2025-05-05 14:30:20,325] {processor.py:153} INFO - Started process (PID=10152) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:30:20,325] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:30:20,325] {logging_mixin.py:115} INFO - [2025-05-05 14:30:20,325] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:30:20,327] {logging_mixin.py:115} INFO - [2025-05-05 14:30:20,326] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 17
    tarefa_2 = PythonOperator(
IndentationError: unexpected indent
[2025-05-05 14:30:20,327] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:30:20,340] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.017 seconds
[2025-05-05 14:30:52,374] {processor.py:153} INFO - Started process (PID=10283) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:30:52,374] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:30:52,375] {logging_mixin.py:115} INFO - [2025-05-05 14:30:52,375] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:30:52,376] {logging_mixin.py:115} INFO - [2025-05-05 14:30:52,375] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 17
    tarefa_2 = PythonOperator(
IndentationError: unexpected indent
[2025-05-05 14:30:52,376] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:30:52,390] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.018 seconds
[2025-05-05 14:31:28,176] {processor.py:153} INFO - Started process (PID=10420) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:31:28,177] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:31:28,177] {logging_mixin.py:115} INFO - [2025-05-05 14:31:28,177] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:31:28,182] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:31:28,190] {logging_mixin.py:115} INFO - [2025-05-05 14:31:28,190] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:31:28,198] {logging_mixin.py:115} INFO - [2025-05-05 14:31:28,198] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:31:28,214] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.039 seconds
[2025-05-05 14:32:02,614] {processor.py:153} INFO - Started process (PID=10585) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:32:02,614] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:32:02,615] {logging_mixin.py:115} INFO - [2025-05-05 14:32:02,615] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:32:02,620] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:32:02,628] {logging_mixin.py:115} INFO - [2025-05-05 14:32:02,628] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:32:02,637] {logging_mixin.py:115} INFO - [2025-05-05 14:32:02,637] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:32:02,647] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.035 seconds
[2025-05-05 14:32:33,666] {processor.py:153} INFO - Started process (PID=10710) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:32:33,667] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:32:33,667] {logging_mixin.py:115} INFO - [2025-05-05 14:32:33,667] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:32:33,672] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:32:33,680] {logging_mixin.py:115} INFO - [2025-05-05 14:32:33,680] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:32:33,689] {logging_mixin.py:115} INFO - [2025-05-05 14:32:33,689] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:32:33,700] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.035 seconds
[2025-05-05 14:33:06,655] {processor.py:153} INFO - Started process (PID=10841) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:33:06,656] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:33:06,656] {logging_mixin.py:115} INFO - [2025-05-05 14:33:06,656] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:33:06,661] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:33:06,669] {logging_mixin.py:115} INFO - [2025-05-05 14:33:06,669] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:33:06,677] {logging_mixin.py:115} INFO - [2025-05-05 14:33:06,677] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:33:06,688] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.035 seconds
[2025-05-05 14:33:41,459] {processor.py:153} INFO - Started process (PID=10974) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:33:41,459] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:33:41,460] {logging_mixin.py:115} INFO - [2025-05-05 14:33:41,459] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:33:41,464] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:33:41,473] {logging_mixin.py:115} INFO - [2025-05-05 14:33:41,472] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:33:41,482] {logging_mixin.py:115} INFO - [2025-05-05 14:33:41,482] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:33:41,491] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.034 seconds
[2025-05-05 14:34:16,202] {processor.py:153} INFO - Started process (PID=11112) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:34:16,203] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:34:16,203] {logging_mixin.py:115} INFO - [2025-05-05 14:34:16,203] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:34:16,210] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:34:16,219] {logging_mixin.py:115} INFO - [2025-05-05 14:34:16,219] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:34:16,230] {logging_mixin.py:115} INFO - [2025-05-05 14:34:16,230] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:34:16,241] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.041 seconds
[2025-05-05 14:34:49,253] {processor.py:153} INFO - Started process (PID=11243) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:34:49,253] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:34:49,254] {logging_mixin.py:115} INFO - [2025-05-05 14:34:49,254] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:34:49,259] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:34:49,267] {logging_mixin.py:115} INFO - [2025-05-05 14:34:49,267] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:34:49,276] {logging_mixin.py:115} INFO - [2025-05-05 14:34:49,276] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:34:49,285] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.034 seconds
[2025-05-05 14:35:22,873] {processor.py:153} INFO - Started process (PID=11439) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:35:22,874] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:35:22,874] {logging_mixin.py:115} INFO - [2025-05-05 14:35:22,874] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:35:22,878] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:35:22,886] {logging_mixin.py:115} INFO - [2025-05-05 14:35:22,886] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:35:22,894] {logging_mixin.py:115} INFO - [2025-05-05 14:35:22,894] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:35:22,904] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.032 seconds
[2025-05-05 14:35:56,778] {processor.py:153} INFO - Started process (PID=11573) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:35:56,778] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:35:56,779] {logging_mixin.py:115} INFO - [2025-05-05 14:35:56,779] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:35:56,783] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:35:56,790] {logging_mixin.py:115} INFO - [2025-05-05 14:35:56,790] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:35:56,799] {logging_mixin.py:115} INFO - [2025-05-05 14:35:56,799] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:35:56,808] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.031 seconds
[2025-05-05 14:36:31,794] {processor.py:153} INFO - Started process (PID=11712) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:36:31,794] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:36:31,795] {logging_mixin.py:115} INFO - [2025-05-05 14:36:31,795] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:36:31,803] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:36:31,817] {logging_mixin.py:115} INFO - [2025-05-05 14:36:31,817] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:36:31,830] {logging_mixin.py:115} INFO - [2025-05-05 14:36:31,830] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:36:31,841] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.050 seconds
[2025-05-05 14:37:04,840] {processor.py:153} INFO - Started process (PID=11854) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:37:04,840] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:37:04,841] {logging_mixin.py:115} INFO - [2025-05-05 14:37:04,840] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:37:04,846] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:37:04,854] {logging_mixin.py:115} INFO - [2025-05-05 14:37:04,854] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:37:04,866] {logging_mixin.py:115} INFO - [2025-05-05 14:37:04,866] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:37:04,877] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.039 seconds
[2025-05-05 14:37:36,248] {processor.py:153} INFO - Started process (PID=11975) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:37:36,248] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:37:36,249] {logging_mixin.py:115} INFO - [2025-05-05 14:37:36,249] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:37:36,253] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:37:36,261] {logging_mixin.py:115} INFO - [2025-05-05 14:37:36,261] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:37:36,270] {logging_mixin.py:115} INFO - [2025-05-05 14:37:36,270] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:37:36,280] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.034 seconds
[2025-05-05 14:38:06,590] {processor.py:153} INFO - Started process (PID=12096) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:38:06,591] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:38:06,591] {logging_mixin.py:115} INFO - [2025-05-05 14:38:06,591] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:38:06,596] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:38:06,604] {logging_mixin.py:115} INFO - [2025-05-05 14:38:06,604] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:38:06,613] {logging_mixin.py:115} INFO - [2025-05-05 14:38:06,613] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:38:06,623] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.035 seconds
[2025-05-05 14:38:40,080] {processor.py:153} INFO - Started process (PID=12225) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:38:40,080] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:38:40,080] {logging_mixin.py:115} INFO - [2025-05-05 14:38:40,080] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:38:40,085] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:38:40,093] {logging_mixin.py:115} INFO - [2025-05-05 14:38:40,093] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:38:40,101] {logging_mixin.py:115} INFO - [2025-05-05 14:38:40,101] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:38:40,111] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.033 seconds
[2025-05-05 14:39:13,694] {processor.py:153} INFO - Started process (PID=12357) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:39:13,694] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:39:13,695] {logging_mixin.py:115} INFO - [2025-05-05 14:39:13,694] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:39:13,699] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:39:13,707] {logging_mixin.py:115} INFO - [2025-05-05 14:39:13,707] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:39:13,715] {logging_mixin.py:115} INFO - [2025-05-05 14:39:13,715] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:39:13,728] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.036 seconds
[2025-05-05 14:39:46,321] {processor.py:153} INFO - Started process (PID=12486) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:39:46,321] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:39:46,322] {logging_mixin.py:115} INFO - [2025-05-05 14:39:46,321] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:39:46,327] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:39:46,334] {logging_mixin.py:115} INFO - [2025-05-05 14:39:46,334] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:39:46,343] {logging_mixin.py:115} INFO - [2025-05-05 14:39:46,343] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:39:46,354] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.035 seconds
[2025-05-05 14:40:20,342] {processor.py:153} INFO - Started process (PID=12625) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:40:20,343] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:40:20,343] {logging_mixin.py:115} INFO - [2025-05-05 14:40:20,343] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:40:20,348] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:40:20,355] {logging_mixin.py:115} INFO - [2025-05-05 14:40:20,355] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:40:20,364] {logging_mixin.py:115} INFO - [2025-05-05 14:40:20,364] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:40:20,374] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.034 seconds
[2025-05-05 14:40:54,461] {processor.py:153} INFO - Started process (PID=12755) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:40:54,462] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:40:54,462] {logging_mixin.py:115} INFO - [2025-05-05 14:40:54,462] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:40:54,467] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:40:54,474] {logging_mixin.py:115} INFO - [2025-05-05 14:40:54,474] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:40:54,483] {logging_mixin.py:115} INFO - [2025-05-05 14:40:54,483] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:40:54,494] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.034 seconds
[2025-05-05 14:41:28,620] {processor.py:153} INFO - Started process (PID=12893) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:41:28,621] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:41:28,621] {logging_mixin.py:115} INFO - [2025-05-05 14:41:28,621] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:41:28,626] {logging_mixin.py:115} INFO - [2025-05-05 14:41:28,626] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 8, in <module>
    import pandas as pd # Biblioteca para manipulação de dados
ModuleNotFoundError: No module named 'pandas'
[2025-05-05 14:41:28,626] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:41:28,639] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.020 seconds
[2025-05-05 14:42:02,274] {processor.py:153} INFO - Started process (PID=13024) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:42:02,275] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:42:02,275] {logging_mixin.py:115} INFO - [2025-05-05 14:42:02,275] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:42:02,280] {logging_mixin.py:115} INFO - [2025-05-05 14:42:02,280] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 8, in <module>
    import pandas as pd # Biblioteca para manipulação de dados
ModuleNotFoundError: No module named 'pandas'
[2025-05-05 14:42:02,280] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:42:02,292] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.019 seconds
[2025-05-05 14:42:35,946] {processor.py:153} INFO - Started process (PID=13156) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:42:35,947] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:42:35,947] {logging_mixin.py:115} INFO - [2025-05-05 14:42:35,947] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:42:35,952] {logging_mixin.py:115} INFO - [2025-05-05 14:42:35,951] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 8, in <module>
    import pandas as pd # Biblioteca para manipulação de dados
ModuleNotFoundError: No module named 'pandas'
[2025-05-05 14:42:35,952] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:42:35,966] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.021 seconds
[2025-05-05 14:43:11,865] {processor.py:153} INFO - Started process (PID=13300) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:43:11,866] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:43:11,866] {logging_mixin.py:115} INFO - [2025-05-05 14:43:11,866] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:43:11,870] {logging_mixin.py:115} INFO - [2025-05-05 14:43:11,870] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 8, in <module>
    import pandas as pd # Biblioteca para manipulação de dados
ModuleNotFoundError: No module named 'pandas'
[2025-05-05 14:43:11,870] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:43:11,882] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.018 seconds
[2025-05-05 14:43:45,470] {processor.py:153} INFO - Started process (PID=13580) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:43:45,470] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:43:45,470] {logging_mixin.py:115} INFO - [2025-05-05 14:43:45,470] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:43:45,837] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:43:45,842] {logging_mixin.py:115} INFO - [2025-05-05 14:43:45,842] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:43:45,851] {logging_mixin.py:115} INFO - [2025-05-05 14:43:45,851] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:43:45,866] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.398 seconds
[2025-05-05 14:44:21,605] {processor.py:153} INFO - Started process (PID=13732) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:44:21,606] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:44:21,606] {logging_mixin.py:115} INFO - [2025-05-05 14:44:21,606] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:44:21,916] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:44:21,922] {logging_mixin.py:115} INFO - [2025-05-05 14:44:21,922] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:44:21,932] {logging_mixin.py:115} INFO - [2025-05-05 14:44:21,932] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:44:21,941] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.338 seconds
[2025-05-05 14:44:52,693] {processor.py:153} INFO - Started process (PID=13868) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:44:52,694] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:44:52,694] {logging_mixin.py:115} INFO - [2025-05-05 14:44:52,694] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:44:53,015] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:44:53,023] {logging_mixin.py:115} INFO - [2025-05-05 14:44:53,023] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:44:53,034] {logging_mixin.py:115} INFO - [2025-05-05 14:44:53,034] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:44:53,043] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.351 seconds
[2025-05-05 14:45:24,829] {processor.py:153} INFO - Started process (PID=14013) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:45:24,830] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:45:24,830] {logging_mixin.py:115} INFO - [2025-05-05 14:45:24,830] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:45:25,159] {logging_mixin.py:115} INFO - [2025-05-05 14:45:25,158] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 48, in <module>
    tarefa_1 >> tarefa_2
NameError: name 'tarefa_2' is not defined
[2025-05-05 14:45:25,159] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:45:25,171] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.343 seconds
[2025-05-05 14:46:00,467] {processor.py:153} INFO - Started process (PID=14166) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:46:00,468] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:46:00,468] {logging_mixin.py:115} INFO - [2025-05-05 14:46:00,468] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:46:00,754] {logging_mixin.py:115} INFO - [2025-05-05 14:46:00,753] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 48, in <module>
    tarefa_1 >> tarefa_2
NameError: name 'tarefa_2' is not defined
[2025-05-05 14:46:00,754] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:46:00,766] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.301 seconds
[2025-05-05 14:46:33,394] {processor.py:153} INFO - Started process (PID=14310) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:46:33,395] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:46:33,395] {logging_mixin.py:115} INFO - [2025-05-05 14:46:33,395] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:46:33,704] {logging_mixin.py:115} INFO - [2025-05-05 14:46:33,703] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 48, in <module>
    tarefa_1 >> tarefa_2
NameError: name 'tarefa_2' is not defined
[2025-05-05 14:46:33,704] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:46:33,716] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.324 seconds
[2025-05-05 14:47:06,017] {processor.py:153} INFO - Started process (PID=14454) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:47:06,017] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:47:06,018] {logging_mixin.py:115} INFO - [2025-05-05 14:47:06,018] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:47:06,310] {logging_mixin.py:115} INFO - [2025-05-05 14:47:06,310] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 48, in <module>
    tarefa_1 >> tarefa_2
NameError: name 'tarefa_2' is not defined
[2025-05-05 14:47:06,310] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:47:06,325] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.309 seconds
[2025-05-05 14:47:38,238] {processor.py:153} INFO - Started process (PID=14599) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:47:38,239] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:47:38,239] {logging_mixin.py:115} INFO - [2025-05-05 14:47:38,239] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:47:38,524] {logging_mixin.py:115} INFO - [2025-05-05 14:47:38,523] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 48, in <module>
    tarefa_1 >> tarefa_2
NameError: name 'tarefa_2' is not defined
[2025-05-05 14:47:38,524] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:47:38,536] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.299 seconds
[2025-05-05 14:48:11,268] {processor.py:153} INFO - Started process (PID=14745) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:48:11,269] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:48:11,269] {logging_mixin.py:115} INFO - [2025-05-05 14:48:11,269] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:48:11,568] {logging_mixin.py:115} INFO - [2025-05-05 14:48:11,568] {dagbag.py:320} ERROR - Failed to import: /root/Documents/airflowalu/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Documents/airflowalu/dags/dados_climaticos.py", line 48, in <module>
    tarefa_1 >> tarefa_2
NameError: name 'tarefa_2' is not defined
[2025-05-05 14:48:11,568] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:48:11,581] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.314 seconds
[2025-05-05 14:48:42,705] {processor.py:153} INFO - Started process (PID=14882) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:48:42,706] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:48:42,707] {logging_mixin.py:115} INFO - [2025-05-05 14:48:42,707] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:48:43,150] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:48:43,190] {logging_mixin.py:115} INFO - [2025-05-05 14:48:43,190] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:48:43,204] {logging_mixin.py:115} INFO - [2025-05-05 14:48:43,204] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:48:43,225] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.522 seconds
[2025-05-05 14:49:20,778] {processor.py:153} INFO - Started process (PID=15042) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:49:20,779] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:49:20,779] {logging_mixin.py:115} INFO - [2025-05-05 14:49:20,779] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:49:21,073] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:49:21,081] {logging_mixin.py:115} INFO - [2025-05-05 14:49:21,080] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:49:21,090] {logging_mixin.py:115} INFO - [2025-05-05 14:49:21,090] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:49:21,101] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.325 seconds
[2025-05-05 14:49:56,678] {processor.py:153} INFO - Started process (PID=15202) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:49:56,679] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:49:56,679] {logging_mixin.py:115} INFO - [2025-05-05 14:49:56,679] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:49:56,970] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:49:56,979] {logging_mixin.py:115} INFO - [2025-05-05 14:49:56,979] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:49:56,990] {logging_mixin.py:115} INFO - [2025-05-05 14:49:56,990] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:49:57,003] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.327 seconds
[2025-05-05 14:50:31,481] {processor.py:153} INFO - Started process (PID=15354) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:50:31,482] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:50:31,482] {logging_mixin.py:115} INFO - [2025-05-05 14:50:31,482] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:50:31,757] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:50:31,764] {logging_mixin.py:115} INFO - [2025-05-05 14:50:31,764] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:50:31,773] {logging_mixin.py:115} INFO - [2025-05-05 14:50:31,773] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:50:31,782] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.302 seconds
[2025-05-05 14:51:03,689] {processor.py:153} INFO - Started process (PID=15492) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:51:03,690] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:51:03,690] {logging_mixin.py:115} INFO - [2025-05-05 14:51:03,690] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:51:03,987] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:51:03,997] {logging_mixin.py:115} INFO - [2025-05-05 14:51:03,996] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:51:04,007] {logging_mixin.py:115} INFO - [2025-05-05 14:51:04,007] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:51:04,018] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.330 seconds
[2025-05-05 14:51:37,152] {processor.py:153} INFO - Started process (PID=15637) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:51:37,153] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:51:37,153] {logging_mixin.py:115} INFO - [2025-05-05 14:51:37,153] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:51:37,420] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:51:37,427] {logging_mixin.py:115} INFO - [2025-05-05 14:51:37,427] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:51:37,436] {logging_mixin.py:115} INFO - [2025-05-05 14:51:37,436] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:51:37,446] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.296 seconds
[2025-05-05 14:52:10,338] {processor.py:153} INFO - Started process (PID=15788) to work on /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:52:10,338] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/dags/dados_climaticos.py for tasks to queue
[2025-05-05 14:52:10,339] {logging_mixin.py:115} INFO - [2025-05-05 14:52:10,339] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:52:10,626] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /root/Documents/airflowalu/dags/dados_climaticos.py
[2025-05-05 14:52:10,635] {logging_mixin.py:115} INFO - [2025-05-05 14:52:10,635] {dag.py:2379} INFO - Sync 1 DAGs
[2025-05-05 14:52:10,646] {logging_mixin.py:115} INFO - [2025-05-05 14:52:10,646] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2025-05-05T00:00:00+00:00, run_after=2025-05-12T00:00:00+00:00
[2025-05-05 14:52:10,655] {processor.py:161} INFO - Processing /root/Documents/airflowalu/dags/dados_climaticos.py took 0.319 seconds
